name: FeelGood
favicon: null
layout_spectrum: 0.07183128478936851
typography_spectrum: 0.6871707448735833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.573407823452726
  lightness: 0.8343214092310518
  saturation: 0.6904777036979795
  rhythmicContrast: 0.29078235593624413
purpose: []
