name: FeelGood
favicon: null
layout_spectrum: 0.07183128478936851
typography_spectrum: 0.62603
title: FeelGood Media Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c59800'
    - '#005a8e'
    - '#2fc3fc'
  brandStrength: 0.5625
  lightness: 0.8343214092310518
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
